(source gnu)
(source melpa)
(source marmalade)

(depends-on "exec-path-from-shell")
(depends-on "haskell-mode")
(depends-on "ghc")
(depends-on "company")
(depends-on "company-ghc")
(depends-on "solarized-theme")
(depends-on "slime")
(depends-on "sml-mode")
(depends-on "tuareg")
(depends-on "utop")
(depends-on "merlin")
(depends-on "auto-complete")